# License: GNU General Public License, Version 3, 29 June 2007
# Copyright © 2022 Helmholtz Centre Potsdam GFZ German Research Centre for
# Geosciences, Potsdam, Germany

#!/usr/bin/env python
# coding: utf-8

'''
    Convert grid to vtk files
'''
import os
import sys
import glob

import numpy as np

from pyevtk.hl import gridToVTK
from pyevtk.vtk import VtkGroup

vtkg = VtkGroup("sim")
vtsfile = "sim0000"
t_sim = 0

# grid dimensions
MODELDIMENSION = [48550, 41420, 1050]

nx = int((MODELDIMENSION[0])/250)
ny = int((MODELDIMENSION[1])/250)
nz = int((MODELDIMENSION[2])/2)

def print_help():
    '''
        Help text
    '''
    text = '''
Call: \033[1mpython grid2vtk.py [OPTIONS] FILE [FILE: model partitions]\033[0m

This script generates a vtk file of a 3d model grid generated by GEOMODELATOR
and/or used by TRANSPORTSE. The output are vtk compatible files.

Example

    python grid2vtk.py --config=config.py model_partitions.npz 

FILE

    GEOMODELATOR numpy output \033[1mmodel partition file \033[0m should be
    numpy compressed format and the array name should be "data" or "array1".
    Additional the array "cell_ids" can be considered. The script can process
    multiple files which should have different filenames.
 
OPTIONS

    --config=FILENAME
        FILENAME should be a geomodelator \033[1mmodel config file\033[0m which then
        will be used to set the model discretization and dimension. If no file is
        used initialize the model settings inside of this script by customizing
        MODELDIMENSION, nx, ny, nz.

    --grid=FILENAME
        FILENAME should be a geomodelator grid in compressend numpy fromat.

'''
    print(text)
    sys.exit()

all_data = {}

# check mandatory input file
if len(sys.argv) < 2:
    print('\033[1mError: Input file missing!\033[0m')
    print_help()

for filename in sys.argv[1:]:

    if len(filename.split('=', maxsplit=1)) == 1:
        with np.load(filename) as data:
            # if 'cell_ids' in data:
                # all_data['cid'] = data['cell_ids'].astype(int)

            data_name = 'unfixable'
            if data_name in data:
                all_data[data_name] = data[data_name].astype(int)

            data_name = 'cell_ids'
            if data_name in data:
                all_data[data_name] = data[data_name].astype(int)

            data_name = 'data'
            if data_name in data:
                all_data[data_name] = data[data_name].astype(int)

            data_name = 'array1'
            if data_name in data:
                all_data[data_name] = data[data_name].astype(int)

            L_name = filename.split('.', maxsplit=1)[0].split('_')[-1]

    elif filename.split('=', maxsplit=1)[0] == '--grid':
        # import geomodelator model_coordinates.py
        filename = filename.split('=', maxsplit=1)[1]
        with np.load(filename) as data:
            data_name = 'x'
            if data_name in data:
                x = data[data_name].astype(float)

            data_name = 'y'
            if data_name in data:
                y = data[data_name].astype(float)

            data_name = 'z'
            if data_name in data:
                z = data[data_name].astype(float)

    elif filename.split('=', maxsplit=1)[0] == '--config':
        # import geomodelator config.py
        cfile = os.path.basename(filename.split('=')[1]).split('.')[0]
        cdir = os.path.dirname(filename.split('=')[1])
        if os.path.dirname(filename.split('=')[1]) != "":
            cdir += "/"

        sys.path.insert(0, cdir)

        filenamelist = sorted(glob.glob(cdir + cfile + '.py'))
        if not filenamelist:
            print('\033[1mError: Config file does not exist!\033[0m')
            print_help()
            sys.exit(1)

        cfg = __import__(cfile)

        nx = cfg.nx
        ny = cfg.ny
        nz = cfg.nz

        MODELDIMENSION[0] = cfg.MODELDIMENSION[0]
        MODELDIMENSION[1] = cfg.MODELDIMENSION[1]
        MODELDIMENSION[2] = cfg.MODELDIMENSION[2]

        dx = np.ones((nx)) * MODELDIMENSION[0] / nx
        dy = np.ones((ny)) * MODELDIMENSION[1] / ny
        dz = np.ones((nz)) * MODELDIMENSION[2] / nz

        # Coordinates
        X = np.cumsum(np.append([0], dx))
        Y = np.cumsum(np.append([0], dy))
        Z = np.cumsum(np.append([0], dz))

        x = np.zeros((nz + 1, ny + 1, nx + 1))
        y = np.zeros((nz + 1, ny + 1, nx + 1))
        z = np.zeros((nz + 1, ny + 1, nx + 1))

        for i in range(nx + 1):
            for j in range(ny + 1):
                for k in range(nz + 1):
                    x[k,j,i] = X[i]
                    y[k,j,i] = Y[j]
                    z[k,j,i] = Z[k]


gridToVTK(
    vtsfile,
    x,
    y,
    z,
    cellData = all_data
)

# add vts to pvd file
vtkg.addFile(filepath = vtsfile+".vts", sim_time = t_sim)

# save pvd file
vtkg.save()
